# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details
# used Silverstripe Translatable as a guide

language: php
php:
 - 5.5
 - 5.6
 - 7.0

sudo: false

env:
 - DB=MYSQL CORE_RELEASE=3.1
 - DB=MYSQL CORE_RELEASE=3.2 PDO=1
 - DB=MYSQL CORE_RELEASE=3.3 PDO=1
 - DB=MYSQL CORE_RELEASE=master PDO=1
 - DB=PGSQL CORE_RELEASE=master

matrix:
  allow_failures:
    - php: 7.0
  exclude:
   - php: 7.0
     env: DB=MYSQL CORE_RELEASE=3.1
   - php: 7.0
     env: DB=MYSQL CORE_RELEASE=3.2 PDO=1
   - php: 7.0
     env: DB=MYSQL CORE_RELEASE=3.3 PDO=1

before_script:
 - phpenv rehash
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
 - cd ~/builds/ss

script: 
 - vendor/bin/phpunit shop_bankdeposit/tests/